import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from '../styles/Header.module.css';
import { headers } from "next/headers";
import { SetStateAction } from "react";
import Right from './Right'; 
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{

  return (
    <html lang="en">
      <body className={inter.className}>
      <header className={styles.headers}>
        <div className={styles.main}>
          <div className={styles.Left}>
            <Link href={"/"}><h1>TranslatePad</h1> </Link>
            <nav>
              <a href="">Blog</a>
              <a href="">Documentation</a>
              <a href="">Features</a>
            </nav>
          </div>
          <Right></Right>
        </div>
      </header>
      <main  className="flex min-h-screen flex-col items-center justify-between p-24">{children}</main>
      
      </body>
    </html>
  );
}