import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from '../styles/Header.module.css';
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className={styles.headers}>
        <div className={styles.main}>
          <div className={styles.Left}>
            <h1>TranslatePad</h1> 
            <nav>
              <a href="">Blog</a>
              <a href="">Documentation</a>
              <a href="">Features</a>
            </nav>
          </div>
          <div className={styles.Right}>
            <button className={styles.Login}>Login</button>
            <button className={styles.Sign}>Sign up</button>
          </div>
        </div>
      </header>
      {children}
      </body>
    </html>
  );
}
